name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libcurl4-openssl-dev pkg-config libssl-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo Check
        run: cargo check

      - name: Cargo Build
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            cargo build --release
          else
            cargo build
          fi

      - name: Cargo Test
        run: cargo test
