name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends cmake build-essential libcurl4-openssl-dev pkg-config libssl-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo Check
        run: cargo check --all-targets --all-features

      - name: Cargo Formatting
        run: cargo fmt --all -- --check
      
      - name: Cargo Test
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            cargo test --release
          else
            cargo test
          fi
